name: model
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: 'none'

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.3
  meta: ^1.9.1
  logger: ^2.0.1
  timeago: ^3.5.0
  string_extensions: ^0.6.12
  html_unescape: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.3